### ISSUE TITLE
Engage on social media: "Call to Experiment" on Unity Forums, Reddit, Itch, Slack, etc.

### ISSUE THREAD

**Issue by delapuente** [MozillaReality/unity-webxr-export#107]
@caseyyee can you give me a list of links for the contribution channels (Twitter, Slack, IRC...)?

**Comment by cvan** [comment]
see the last two pages of https://docs.google.com/document/d/1Y0zSqiObKei4F1J3BWFIyAG7r5gHazQe3bWbrIuL5W0/edit
