### ISSUE TITLE
Evaluate Neocities as recommend hosting option

### ISSUE THREAD

**Issue by cvan** [MozillaReality/unity-webxr-export#111]
https://neocities.org/ is a reliable host and very easy to use (without needing any CLI knowledge, though there is a real nice [CLI assistant](https://twitter.com/neocities/status/865616680109490176)).

There are evidently some limitations for hosting Unity WebVR-exported games (with file size, I believe). @delapuente: can you tell me what you encountered? We'll try to reach out to [Kyle](https://twitter.com/kyledrake) at Neocities

<hr>

Relevant to documentation written by @delapuente in PR #109

**Comment by delapuente** [comment]
Great! Limits for free hosting are not bad (1GiB store / 200GiB bandwidth) but it rejects uploading `*.webmanifest` and `*.asm.*` and `*.wasm.*` files.

**Comment by cvan** [comment]
@kyledrake: howdy! hope all is well! would there be any chance you can have Neocities whitelist those above file extensions as well as `*.unityweb` files (for WebAssembly modules)?
