### ISSUE TITLE
Rename project to `unity-webvr-exporter`?

### ISSUE THREAD

**Issue by cvan** [MozillaReality/unity-webxr-export#122]
`unity-webvr-exporter` vs. `unity-webvr-export`

**Comment by delapuente** [comment]
Or `unity-webvr-assets`.

**Comment by cvan** [comment]
yeah, the latter makes more sense now (especially since the package is now published to UAE)

**Comment by caseyyee** [comment]
I'd prefer _assets_, but that was already taken by @gtk2k. Might also reconsider `webvr` since we've generally made the change to XR?
