### ISSUE TITLE
Create teleportation interaction in example scene

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/unity-webxr-export#203]
Teleport within scene.

**Comment by cvan** [comment]
For those curious, this is what VR teleportation typically looks like:

![image](https://user-images.githubusercontent.com/203725/37636385-220169d0-2bbf-11e8-999b-7398a1ed9e33.png)

Here's a good article written on the topic by @fernandojsg: https://blog.mozvr.com/developing-an-aframe-teleport-component/

Also, see in the Vive lobby how teleportation works with the trackpad on the VR controllers.

**Comment by andrasbalazs** [comment]
Is this feature is still unsolved in the current version? :)
