### ISSUE TITLE
Explore integration with VRTK

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/unity-webxr-export#23]
https://github.com/thestonefox/VRTK

It would be nice to be able to utilize toolkit components rather than re-building our own.

**Comment by timokorkalainen** [comment]
This would be superb! Most likely a proper integration would "just" require to build this repo as an SDK setup for VRTK. This is, a set of components that provide VRTK the correct data on headset & controller poses and interactions.

**Comment by caseyyee** [comment]
@timokorkalainen that's the idea.   I'm not totally up to speed on how to create a SDK for VRTK, but any pointers or ideas on how to get started, i'd love to hear it :)  Accepting contributions as well of course!

**Comment by caseyyee** [comment]
Seems like the VRTK project is winding down.

Here's another option:
https://github.com/TomorrowTodayLabs/NewtonVR
