### ISSUE TITLE
get export working on Samsung Gear VR (S8 or better)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/unity-webxr-export#25]

**Comment by caseyyee** [comment]
Mobile enabled in https://github.com/caseyyee/unity-webvr-export/commit/f4f467f2b049e039683592a1e55e23e40fc38336

I think just needs to be tested.   Might work, but perf expected to need tweaks.

Also would be good to document exactly the limitations here.

**Comment by delapuente** [comment]
If we are including this, then we should document the Gear VR controller too. Just remember to add it in #86

**Comment by caseyyee** [comment]
Mobile is officially not supported by the unity player.   Taking this out of the community release until we can get further testing done around mobile support.  We already have notes in compatibility section in readme that say this.

**Comment by cvan** [comment]
> Mobile is officially not supported by the unity player. Taking this out of the community release until we can get further testing done around mobile support. We already have notes in compatibility section in readme that say this.

is there any relevant info or links we can surface about this? I'm sure this question will come up often. and with the new mobile headsets coming out, I'm sure this will become more of a requested item.

**Comment by caseyyee** [comment]
Ah good call.

https://docs.unity3d.com/Manual/webgl-browsercompatibility.html

See second paragraph note.

**Comment by cvan** [comment]
can you link to this from the `README`? and perhaps as a comment in the [JS here](https://github.com/caseyyee/unity-webvr-export/blob/b6a39c1/Assets/WebGLTemplates/WebVR/index.html#L14) as well?
