### ISSUE TITLE
Add documentation about using A-Frame scenes with Unity

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/unity-webxr-export#281]
This has been brought up a few times in the #unity slack.   We should include some notes on moving between A-Frame and Unity pages and detail what is or isn't possible. 

example from _saltzshaker_:
https://best-hoof.glitch.me/
![image](https://user-images.githubusercontent.com/1560884/39972928-33afa352-56cd-11e8-85bc-1435b9b6c6dd.png)

This won't work since A-Frame and Unity have their own renders are will not composite together into the headset.  Though interestingly, this will work in 2D since they both will fall back to polyfill.

**Comment by Utopiah** [comment]
Indeed, and overall what is the recommend way to extend an export e.g. using existing threejs or even A-Frame components as already started with https://github.com/mozilla/unity-webvr-export/blob/master/docs/customization/adding-ga.md
