### ISSUE TITLE
Multiplayer Networking 

### ISSUE THREAD

**Issue by jeffrobernard** [MozillaReality/unity-webxr-export#286]
Hello, how is multiplayer networking for weber within unity handled? Can you use photon or is there another more simple way of implementing it? Also, I was messing around with Mozilla hubs and it seems like that would be useful it it were incorporated into Unity WebVr build. Looking for any input on a road to go down on this. Thanks!

**Comment by HeadClot** [comment]
You could use [websocket sharp](https://github.com/sta/websocket-sharp) and Node.js.

**Comment by caseyyee** [comment]
Focusing on just the basics for now, but would love to incorporate web-based multiplayer networking. Unsure if existing Unity solutions will work within the browser as-is. Would love to hear if anyone has any luck with this.
