### ISSUE TITLE
Performance in browser (unaccounted time?)

### ISSUE THREAD

**Issue by omgitsraven** [MozillaReality/unity-webxr-export#287]
Performance when compiling to the browser, even just in the test scene, is typically very bad for me, taking around 24ms on average (compared to around 12ms when testing in the editor). I understand that CPU-bound tasks are going to take longer in the browser, but is *that* much of a difference really expected?

I ask also because typically, in the profiler, almost half (and sometimes *over* half) the frame time in WebGL builds is taken up by a section that just says `Unaccounted time between: PostLateUpdate.ProfilerEndFrame and GC.Alloc 13.00ms` (or however long). I'm still new to Unity's profiler, but is that expected or does it seem like something is going wrong and stalling rendering for some reason?

**Comment by cvan** [comment]
cc @caseyyee

**Comment by caseyyee** [comment]
Just getting to this now.
@omgitsraven have you tested standard (non WebVVR) WebGL content to see if we are encountering the same performance issues?  Just getting around to focusing on some performance updates now.  Also new to this, so any resources you have been looking at for profiling will help me as well.
