### ISSUE TITLE
Support for Oculus Remote

### ISSUE THREAD

**Issue by cflorea1** [MozillaReality/unity-webxr-export#301]
I am unsuccessful in using the Oculus Remote.

Input.GetJoystickNames() and Input.GetKey(KeyCode.Joystick1Button0) both return nothing.

Unity documentation: https://docs.unity3d.com/Manual/OculusControllers.html

**Comment by cvan** [comment]
thanks for reporting this issue! when I dig mine up and find it, I'll make sure to look at this. thanks again :+1:

**Comment by caseyyee** [comment]
@cflorea1 does the remote show up with http://html5gamepad.com/ ?

Also, just so I have the right controller, is this the one you're referring to?

![image](https://user-images.githubusercontent.com/1560884/42122382-d289c1ae-7bf5-11e8-8258-3db39e0f3164.png)

**Comment by cvan** [comment]
@caseyyee: if you call 

```is
let gamepads = {};
gamepads.mappings = {
  'Oculus Remote': {
    buttons: {
      0: 'center',
      1: 'back',
      2: 'up',
      3: 'down',
      5: 'right',
      4: 'left'
    }
  }
};
gamepads.states = {
  'Oculus Remote': {
    buttons: {
    }
  }
};

navigator.getVRDisplays().then(displays => {
  // Poll gamepads in the rAF game loop.
  updateGamepadState();
});

function updateGamepadState () {
  const oculusRemote = navigator.getGamepads().find(g => g.id === 'Oculus Remote');
  if (!oculusRemote) {
    return;
  }
  const buttonsMapping = gamepads.mappings[oculusRemote.id].buttons;
  let buttonName;
  for (let idx = 0; idx < buttonsMapping.length; idx++) {
    buttonName = buttonsMapping[idx];
    gamepads.states[oculusRemote.id].buttons[buttonName] = oculusRemote.buttons[idx].pressed;
  }
});
```
you can also check out this old code I wrote: https://github.com/MozillaReality/oculus/blob/master/assets/js/gamepad.js

but yeah hope those mappings help. lmk! thanks, @caseyyee :+1:
