### ISSUE TITLE
Unity shows Javascript compile errors on start

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/unity-webxr-export#340]
![image](https://user-images.githubusercontent.com/1560884/45769996-14327480-bbf6-11e8-9687-65835b623545.png)

![image](https://user-images.githubusercontent.com/1560884/45770064-39bf7e00-bbf6-11e8-99fd-899a59b3b1f1.png)

There have been suggestions on the Unity slack channel that the error is caused by the last open file.

**Comment by caseyyee** [comment]
@JacobHegwood Issues take time, matter of priority!
I find that closing and re-opening Unity seems to clear the errors for me.  Unsure how to fix this at the moment, maybe Unity has some kind of exclusion that you can add to not parse the Javascript when in Unity editor.

**Comment by githubcatw** [comment]
I also get the same, but this time all of the JavaScripts error out.
Here is an excerpt from the editor log - [link](https://pastebin.com/raw/uH9E3c2H)
