### ISSUE TITLE
What is the bare minimum to enable WebVR?

### ISSUE THREAD

**Issue by StephenHodgson** [MozillaReality/unity-webxr-export#345]
Hi,

I was wondering what the bare minimum needed to enable WebVR?

I was hoping to use this in another project, but when I try to import it via asset store there's lots of folders that get added to the project.

![image](https://user-images.githubusercontent.com/13334553/47262356-a353d600-d49b-11e8-995b-fa42df68682f.png)

**Comment by caseyyee** [comment]
Yes, you can leave those all out.

Are you importing the package from the Asset store or somewhere else? Those directories should have been left out.

**Comment by caseyyee** [comment]
Ah yes, looks like the one in the asset store includes those directories. the unitypackage in the repo only includes the `WebGLTemplates` and `WebVR` directory.

**Comment by StephenHodgson** [comment]
Where are the locations for those packages?

I was looking though the release tab, but it only had source.

**Comment by caseyyee** [comment]
The `WebVR-Assets.unitypackage` is located in the main directory of the repo:
https://github.com/mozilla/unity-webvr-export/blob/master/WebVR-Assets.unitypackage

Instructions for importing them are in the getting started docs: https://github.com/mozilla/unity-webvr-export/blob/master/docs/project-setup.md#4-download-the-assets-from-the-unity-asset-store

**Comment by caseyyee** [comment]
@StephenHodgson Ah yes, I think putting a link directly to the package from somewhere on the front page readme will be useful.
