### ISSUE TITLE
Needs updates for 2018.3?

### ISSUE THREAD

**Issue by wimachtendink** [MozillaReality/unity-webxr-export#349]
Hello,

I only did a quick search for issues here, so I apologize if this is redundant.

Has anyone else found this asset unresponsive/not working for 2018.3?

I didn't get any error messages or anything, but there didn't seem to be any connection between SteamVR and Unity when using this as a plugin from the asset store.

Thanks for your time.

**Comment by cstensonpv** [comment]
I get: exception thrown: RuntimeError: memory access out of bounds in 2018.3 any tips?

**Comment by caseyyee** [comment]
Interesting. unsure what this might be caused by.  Have you tried rolling back Unity version to check for sure this is 2018.3 specifically?
