### ISSUE TITLE
[proposed labels: bug, help wanted, Windows Mixed Reality] WebVR Unity does not work with Windows Mixed Reality headsets (error WEBVR22602)

### ISSUE THREAD

**Issue by pgpalafox** [MozillaReality/unity-webxr-export#353]
Hi,

I have'nt managed to make it work this system/Unity asset with a Windows Mixed Reality (WMR) headset, trying on several different computers and headset (Lenovo and HP). I do not know if this system is still maintained here, because I see very few movement in yours threads, but any help will be welcome.

Browser:
  Edge: Microsoft EdgeHTML 17.17134, 42.17134.1.0

Unity tested version:
  2018.2.20f1
  2018.3.6f1
  2019.2.0a8

System
  Windows 10 Pro, see. 1803 - 17134,648
  16 GB Ram
  NVIDIA GeForce GTX 1060, 6 GB

Headset tested
  Lenovo and HP Windows Mixed Reality Systems

Tests
-------

The first thing is that the example page https://mozilla.github.io/unity-webvr-export/ does not work with the tested systems, it gives javascript error in the file telemetry.js
```

SCRIPT5022: SCRIPT5022: SyntaxError
telemetry.js (153,7)
  Invoking error handler due to SyntaxError
```

To make it work, I have disabled it by adding line 236 in the isTelemetryDisabled function

 ` return true;`

which causes the file not to be processed.

Once that problem is solved, the WebGL environment appears correctly in the browser, but when I push in the visor button to see the WebGL image in the headset, it gives the error

```
Unable to enter VR mode: undefined
webvr.js (103.7)

  WEBVR22602: VRDisplay.requestPresent is rejected - presenting HTMLCanvasElement's context is not compatible with the VRDisplay. Event.preventDefault () must be called during the firing of the webglcontextlost event on the presenting HTMLCanvasElement.
```

and dont activate any in the headset.

Making the compilation following the steps of https://github.com/mozilla/unity-webvr-export/blob/master/docs/project-setup.md, they still give the same errors, that of telemetry.js (solved by adding the mentioned line) and WEBVR22602 (unresolved).

I have tried to download the AssetStore asset and directly the GitHub version. Allways the same problems.

To make the tests the headset is connected and working.

The same system works perfectly with other WebVR examples of A-frame or playcanvas.

I have no doubt that the Unity asset works with HTC Vive and Oculus systems, but I am quite convinced that it's impossible to work with WMR headset systems, or at least I dont known how to make it work.

Please, is there anyone with a Microsoft Mixed Reality headset that could have made it work, and if so, what model?

Any ideas how to make this Unity asset system works withs WMR headsets, or to solve the WEBVR22602 error?

Any help will be welcome. I am make to do debugs if necessary, I'm interested in helping the system work with WMR systems.

A greeting and thanks in advance,

**Comment by SamarShool** [comment]
Ive tried to load the demo scene by uploading to github as is and trying to open on edge in samsung odessey, does not work screen goes black with some bouncing tiny balls in center...works randomly sometimes from latest firefox using steam VR with windows mixed reality on steam vr.
