### ISSUE TITLE
Demo link does not work in Edge?

### ISSUE THREAD

**Issue by foxvalleysoccer** [MozillaReality/unity-webxr-export#356]
This demo link does not work in Edge but does work in Firefox.
https://mozilla.github.io/unity-webvr-export/Build/

I tried building my own demo from the repository too and it also doesn't work in Edge.

SCRIPT5022: SCRIPT5022: SyntaxError telemetry.js (153,7)
http://dev.wisc-online.com/Prototypes/joshLinks/Heart/index.html

Is there a special way to publish for Edge or does it only work in specific versions?

This is my version
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

**Comment by caseyyee** [comment]
There was nothing particularly different to enable Edge support since it implements the standard WebVR API.  Something could have broken in Edge or the exporter in the 2018.x Unity upgrade.  Unfortunately can no longer test as I don't have access to a WMR device.

**Comment by caseyyee** [comment]
Unsure how if this is the same/related issue: https://github.com/mozilla/unity-webvr-export/issues/353

Either change the title if its a new issue to be more specific, or close in favor of 353.

**Comment by riebling** [comment]
Can confirm, Edge in HoloLens throws syntax error in javascript exception, same deploy works on Android, Firefox, Chrome web browsers. Tried debugging but HoloLens is a little tricky to access javascript error consoles :)

**Comment by joshmarinacci** [comment]
Does the new Edge support WebXR?

**Comment by De-Panther** [comment]
@joshmarinacci
https://caniuse.com/#feat=webxr
Should support, but I guess it's the same as Chrome Desktop and you'll need to run it using special configuration.
