### ISSUE TITLE
Problem in the VR Mode

### ISSUE THREAD

**Issue by bromelee** [MozillaReality/unity-webxr-export#357]
Hello, i check this in assets store and looks incredible, i tested in some projects and i get this problem.

![190a37015aa0cc9e9225e961cd794681](https://user-images.githubusercontent.com/20862888/56932090-04421380-6aa8-11e9-888a-d3ca4931617d.png)

The cameras dont appear correctly when i pass to VR Mode.
I dont know if this problem is in unity or in the Javascript codes.

By the way, the gyro works good in mozilla but in chrome the gyro doesnt work.

i see other issues that says to activate the WEBVR flag, i activated and get this.
![ce58515e9ed586da272071f33465a1d6](https://user-images.githubusercontent.com/20862888/56932357-ff319400-6aa8-11e9-9f38-02d81f92095f.png)

Any idea for this problems???

thank for the readers and hope you can help me.

**Comment by TylerCode** [comment]
Still getting this issue in 2020, will be looking into it and will do a PR if I can get it working.

**Comment by ibrews** [comment]
getting a similar error with canvas of null
