### ISSUE TITLE
Resolution Terrible In Firefox/Oculus

### ISSUE THREAD

**Issue by Yarwad** [MozillaReality/unity-webxr-export#358]
When I enter VR the resolution is super low.   It looks fine in my Unity editor but upon playing the build in firefox it looks horrible.  Also the tracking is terrible.  What am I doing wrong?

**Comment by DominikKoller** [comment]
Bump.
Having the same issue, the resolution in VR is terrible / close to unusable and I cant find a setting to change it. Using the Oculus Quest, having the issue both in Firefox Reality and the built in Oculus Browser. 

The browser window size before going into VR mode affects the resolution -> smaller window, worse resolution in VR. 

I tried the Default Canvas Width / Height settings in the Presentation settings to no effect. I cannot find other settings and meddling in the produced javascript hasn't gotten me anywhere yet.

**Comment by lorak41** [comment]
I have the same problem, did you manage to fix this?

**Comment by EduardtAlberg** [comment]
Hi,
i had the same problem with steamvr on desktop pc. On the final build i removed ",o.canvas.style.width="100%" in the UnityLoader.js and changed line 88 of webvr.js from "this.gameContainer.setAttribute('style', `transform: scale(${scaleX}, ${scaleY}); transform-origin: top left;`);" to "this.gameContainer.setAttribute('style', `transform-origin: top left;`);" to get the full size spectator view on browser.

**Comment by AlexUnder2010** [comment]
Hi, any ideas how to fix this? Everything is so pixelated in VR mode, nothing helped, even after adding  "this.canvas.style.removeProperty('width')".

**Comment by uecarlos** [comment]
I have been able to reproduce this error on an Oculus Quest using Firefox Reality:
![org mozilla vrbrowser-20200410-131045 1](https://user-images.githubusercontent.com/29814194/78987217-aaf2b900-7b2d-11ea-9c4b-2cacc5fbf53f.jpg)

For reference here is an screenshot using the Oculus Browser where the image is perfectly clear:
![com oculus browser-20200410-130958 1](https://user-images.githubusercontent.com/29814194/78987211-a62e0500-7b2d-11ea-87fb-34fccb5a31b1.jpg)

**Comment by tvkamara** [comment]
I have the same issue. For my own build of the sample scene, the VR mode is blurry in both the Oculus browser and Firefox Reality. The eye texture goes to around 400x400, I can confirm this using the OVR Metrics tool. For some reason the pre-build sample in the project front page works in Oculus Browser (not blurry) but low quality in Firefox Reality.

For my own build I am using the Asset Store version, downloaded today (April 10).

**Comment by De-Panther** [comment]
@tvkamara do you test your own build on HTTP or HTTPS?
HTTP will use the Polyfill and use the old WebVR where available(e.g. on Oculus Quest), while HTTPS would use WebXR if it's available.

**Comment by tvkamara** [comment]
@De-Panther That is probably it. I used HTTP. What would be easiest way to to disable Polyfill altogether? When debugging, I would rather have it fail than use that option. Thanks.

**Comment by De-Panther** [comment]
In webxr.js init() there's if statement that loads Polyfill if WebXR isn't available. You can remove the else...

Unity's Build and Run use node.js server with HTTP. You might want to run HTTPS server instead, I find that the simplest way for me was to use npm http-server as HTTPS with no cache in the build folder.
`http-server -c-1 -S`
https://www.npmjs.com/package/http-server

**Comment by a567w** [comment]
I have the same issue. 
With Unity 2019 the resolution will be lower.
Oculus Quest + Oculus Browser
Unity 2019.3.9f1  + WebXR Exporter2.0.0  : Low resolution
Unity 2018.4.17f1 + WebXR Exporter2.0.0  : OK

**Comment by fernandojsg** [comment]
fwiw Firefox Reality still doesn't have the WebXR API implemented (although it will come pretty soon :) ). So when testing it there it will use the WebXR polyfill as @De-Panther explained.
I have not been following the WebXR polyfill development, but I got some weird issues on other demos when using it also related to incorrect resolution or canvas size when exiting the VR mode.
I'd recommend for the time being to test it on Oculus Browser and just wait for Firefox Reality to support WebXR (as I said this will come quite soon anyway), to really have a sense of the resolution and performance.

@a567w are you referring to low resolution on Oculus Browser too right? not on Firefox Reality

**Comment by a567w** [comment]
In my own build, Firefox Reality didn't go full screen, so I used Oculus Browser.

The demo at https://mixedreality.mozilla.org/unity-webxr-export/Build/ showed that both Firefox Reality and Oculus Browser had low resolution on the Oculus quest.

Thank you.
