### ISSUE TITLE
Delay causing motion sickness (even on simple scene)??

### ISSUE THREAD

**Issue by guiglass** [MozillaReality/unity-webxr-export#362]
Just tried to build and run a game in FireFox using this plugin and a Vive pro.

I made the scene super simple with a player, a cube and a skybox.

When i ran the game it was very smooth, but tracking was delayed by a small time. Just enough to cause some major vertigo though. 

I am on Windows10, running a I9-9900k cpu, two 2080-Ti gpus and all OC'ed.

Why would there still be so much delay on an empty scene?

The desert scene also has the exact same delay issue.

I believe it has to do with rotation only, and when traversing my head linearly it appears to be realtime, but when turning my head it takes time to catch up (it's sorta like being heavily inebriated, just far less enjoyable).

Is there anything I can do? I don't see any tracking delays when using Sketchfab (even complicated models are fine).

Please help!!

**Comment by Clodo76** [comment]
I have exactly the same issue. I followed exactly the steps of the "Getting Started" guide,
absolute plain "Sunny Desert" scene, with Oculus Quest i see hands, but seem dropping frames (run like  10fps).
Unity 2018.3.6f1 if matter.
Please help!!

**Comment by Clodo76** [comment]
Same issue with "Check out the demo now" (link in readme.md), with Oculus Quest and
the new "Firefox Reality" browser (also made by Mozilla, the same author of this repo).
Other WebVR projects works perfectly.

**Comment by foxvalleysoccer** [comment]
Im having the same issues with Oculus Quest. https://tinyurl.com/qReduced3 Can see my link here.
Anyone solve this issue yet?

**Comment by shane1090** [comment]
Has there been any progress with this issue? I've been looking at developing with WebVR but noticing the tracking is really bad. Seems like this project went dead quite a while ago?

**Comment by HawkenKing** [comment]
I really want to dip my toes into making something with this repo but the comments are putting me off, does it run slowly on the Quest?
