### ISSUE TITLE
Remapping OpenVR inputs 

### ISSUE THREAD

**Issue by alessiograncini** [MozillaReality/unity-webxr-export#364]
Creating the inputs for OpenVR from the unity documentations and mapping them to the Gamepad Ids of the WebVR templates, as suggested in the WebVR repo documentation, I successfully play the scene in Unity having the right response from the controller.

Unfortunately on the Web the controller inputs are not recognized - I still can see them.
[in my scene there are no components referencing VIU when it plays correctly in Unity].

The demo from the repo deos exactly what I did and differently it works. 
I don't get it. 

Do you guys know how to map OpenVR inputs and get them to work properly ? 

![sc1](https://user-images.githubusercontent.com/10515494/59886690-da54f100-9374-11e9-8395-4315133c183c.PNG)
![sc2](https://user-images.githubusercontent.com/10515494/59886691-daed8780-9374-11e9-961c-1fc4d9b961ac.PNG)
![sc3](https://user-images.githubusercontent.com/10515494/59886692-daed8780-9374-11e9-9b02-153e200ba534.PNG)

**Comment by alessiograncini** [comment]
Further update. Got rid of VIU. Indeed, I don't need it. my only goal was mapping the OpenVR inputs on the webVR inputs. Success on Unity at runtime. Not the same on the web. Is there any specific way to do it ?
Thank you.

**Comment by CollinCunningham** [comment]
I'm having the same issue using Oculus inputs - did you ever find a solution?

**Comment by DanhuaZhang** [comment]
Same issue here for Windows Mixed Reality. The input from the grip buttons in Unity seems to be touchpad-press in WebXR.
