### ISSUE TITLE
WebVR build not recognizing Firefox as xrenabled browser, also cant serve locally

### ISSUE THREAD

**Issue by TheBricktop** [MozillaReality/unity-webxr-export#367]
Unity version : 2019.2.2
WebVR export from assetstore
node.js: current LTS 

Hello, im trying to build simple example from WebVR export but ran into two bugs :
1. Unity build and run starts local static server and content is shown properly but it doesnt recognize my firefox browser as vr enabled.
2. trying to serve locally by http-server in node.js starts local server but after entering localhost page Firefox throws error : content cannot be displayed or its broken.

I cant get any answears anywhere about this.

**Comment by skymeson** [comment]
I think I'm having the same issue. I'm using 2019.3.10f1. Directions for enabling VR are for 2017 which is outdated now. I'm not getting any firefox errors though when I run and I'm also serving through node.js.

**Comment by De-Panther** [comment]
Did you run it as HTTP or HTTPS?
HTTP will use Polyfill and might not work on systems that supports only WebXR.
HTTPS will use WebXR if enabled.

If you use node.js http-server, you should call it with -S.
http-server -S
I usually also disable the cache, so something like:
http-server -c-1 -S

**Comment by skymeson** [comment]
Just tried running with https and same issue. I'm wondering about the build settings. In 2019.3 there is no option to enable VR in player settings. Its all handled in XR Plug-in Management, but I don't see any XR plugins available for WebGL platform.  Packages I have installed are XR Plugin Management 3.2.7, XR Legacy Input Helpers 2.1.3, XR Interaction Toolkit 0.9.4, XR Interaction Subsystems 1.0.1 and OpenVR Desktop 2.0.5 plus other standard ones. Am I missing something? Perhaps I should be using different version packages or older version of Unity?
