### ISSUE TITLE
Will Unity-WebVR work with the new Unity XR-Platform?

### ISSUE THREAD

**Issue by Servonius** [MozillaReality/unity-webxr-export#369]
Will Unity-WebVR work with the new Unity XR-Platform?

Here's the blog link for the new XR-Platform of Unity: https://blogs.unity3d.com/2020/01/24/unity-xr-platform-updates/

**Comment by DomenicJahn** [comment]
Currently, it does not.

**Comment by DomenicJahn** [comment]
Currently, it does not. I couldn't get it to work with any version newer than 2018.4.

**Comment by DomenicJahn** [comment]
Currently, it does not. I couldn't get it to work with any version newer than 2019.2.

**Comment by Corysia** [comment]
It does today.  I just tried it with 2019.3.9f1 and XR Plugin Management 3.2.6, XR Legacy Input Helpers 2.1.3, XR Interaction Subsystems 1.0.1, and XR Interaction Toolkit (preview) 0.9.4.
Most importantly, the deprecated VR system was disabled and it worked. I hosted my build with `python -m http.server` from the `Build` directory and connected with my Quest.

**Comment by imbible** [comment]
> It does today. I just tried it with 2019.3.9f1 and XR Plugin Management 3.2.6, XR Legacy Input Helpers 2.1.3, XR Interaction Subsystems 1.0.1, and XR Interaction Toolkit (preview) 0.9.4.
> Most importantly, the deprecated VR system was disabled and it worked. I hosted my build with `python -m http.server` from the `Build` directory and connected with my Quest.

I confirm it is true. I have the webxr build work on my Quest following Corysia's configuration.

**Comment by skymeson** [comment]
This compiles and runs, but VR not enabled for me. I'm using unity 2019.3.10.f1. Instructions for enabling XR are outdated and show unity 2017 setup. Using XR Plug-in Management, I don't see any Plug-in Providers. Do I need to add these somehow or does WebXR handle that?

**Comment by soraryu** [comment]
I think the code as-is just bypasses all XR Management - no providers so far that I can see.

**Comment by samshool** [comment]
im trying to get this plugin to work with windows mixed reality headset samsung odessey, i can only see the scene stuck to the HMD, keeps giving error ...anybody else tried WMR headset with this plugin?

Virtual reality enabled cannot be set while the Editor is in Play mode.
UnityEditorInternal.VR.VREditor:SetVREnabledOnTargetGroup(BuildTargetGroup, Boolean)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
