### ISSUE TITLE
Yikes. A Unity asset package that stomps on my ProjectSettings directory!?

### ISSUE THREAD

**Issue by andybak** [MozillaReality/unity-webxr-export#381]
(this relates to installing via the Asset store)

Luckily I use version control but this could break people's projects. Assets are surely not meant to do that? I've never seen it before.

At the very least the asset store needs a warning in big glowing fiery text right at the top.

I can imagine this seriously breaking people's projects. Some of the changes seem pretty arbitrary and orthogonal to the purpose of this.

Look to see how SteamVR handles it - they have an editor script that offers to update selected settings and allows you to opt out.

**Comment by bddckr** [comment]
The SteamVR plugin actually did this the same way for a long time. I'd argue it's on Unity to resolve UX issues in terms of package importing.

With the move to UPM packages I don't think there is a generic solution to this yet either - everyone seems to continue being forced to roll their own solution to add/modify project-wide settings.

**Comment by fernandojsg** [comment]
Hi @andybak sorry to hear that.
Reading this https://unity3d.com/asset-store/sell-assets/submission-guidelines it seems like Unity should show at least a notification isn't it?
```4.4.f The Project Settings of your project will be automatically included with any submission being uploaded in the “Complete Projects” category or subcategories. Users will receive a notification that their Project Settings will be replaced when importing your project.```

I'm thinking if it would be better to change the project category from `Complete project/system` to something else like `Tools/Integrations` or something else, so it won't try to include the project settings, although I'm not sure about the side effects on that, I'll need to test it.

**Comment by andybak** [comment]
> The SteamVR plugin actually did this the same way for a long time.

I started using SteamVR in 2017 and unless I'm misremembering they were using a script with in opt-out to change settings even back then.

> I'd argue it's on Unity to resolve UX issues in terms of package importing.

I do agree with this. 

In any case the current situation is going to break some projects for the kind of people least able to recover - inexperienced users who don't use version control and have poor back-up discipline. In the short term could you at least add a big warning for those people?

Beyond that - do you have a clear idea what settings changes are essential, which are recommended and which are optional?

Depending on the proportion of each - it might be as simple as documenting them rather than automating things.

**Comment by fernandojsg** [comment]
I have just pushed a new release with the latests PR merged, and also changed the category of the project from `Whole application` to `Scripting/Integration` so it won't include the project settings.
Regarding the settings that should be useful to set are basically two, and I'll document them on the docs:
- InputManager.asset: To do the buttons mapping
- QualitySettings.asset: Not mandatory but useful for performance.

I hope that fixes your problem.
Thanks again for reporting.
