### ISSUE TITLE
Slack URL is broken in README

### ISSUE THREAD

**Issue by skibitsky** [MozillaReality/unity-webxr-export#384]
Hi,

The Slack URL from [Need Help?](https://github.com/MozillaReality/unity-webxr-export/blob/master/README.md#need-help) section of README redirects to [mixedreality.mozilla.org/?hello](https://mixedreality.mozilla.org/?hello) instead of Slack.

**Comment by tz18** [comment]
I think that the public slack may be gone after some staffing changes at Mozilla, not sure
