### ISSUE TITLE
Custom WebGLTemplates

### ISSUE THREAD

**Issue by De-Panther** [MozillaReality/unity-webxr-export#386]
The current WebXR WebGLTemplate is very "hardcoded" and it won't be so easy to customize it.
There are buttons and other DOM elements that it looks for in the HTML page.
Each template should contain important files like the webxr.js, gl-matrix-min.js and webxr-polyfill.js.

Unity doesn't support placement of the WebGLTemplates folder in sub folders, so all the templates must be located under Assets/WebGLTemplates.

The current way of using customize template for your own project, would be to copy the WebXR template and edit it.
It means duplicated code in the project (the important JS files), and hard to maintain code over time - each update of the WebXR Export plugin would need to re edit the template and copy the updated files.

Possible solutions:
- First, remove all the document.getElementById from webxr.js and use events to notify if Immersive Session is supported and if a toggle button clicked.

Then, there are a few options regarding the important JS files:
- We can copy them to StreamingAssets folder, and the HTML page would need to locate them there. If that works, the main issue would be on other platforms (Android, iOS, Desktop, etc...), which won't need those files.
- We can put them in a sub folder of the WebXR folder, and copy them at the end of WebGL build process. Unity no longer supports the old UnityScript so it's ok to use ".js" files in the project. And we might want an option for the developer to configure if the plugin copies them or not.

What do you think? Any other solutions?

**Comment by uecarlos** [comment]
Since the topic has been raised I'd like to nitpick regarding the inconvenience that the template files are processed by Unity (because they are required to be in the Assets folder). This creates .meta files that are not required and triggeres reimporting when working on the WebGL template.

In my fork I have renamed the template to "WebGL~" to prevent Unity from importing and watching those files.

I think this would solve the issue with the ".js" files in the project, since Unity would not care about them.

**Comment by De-Panther** [comment]
Good point regarding the tilde "~", but I'm not sure if files in that folder would be able to get into the unitypackage file. (supporting Unity Package Manager is another discussion)

When I'm working on the JS and HTML files, I work on the build folder, then I don't need to build again the project just to test those. I do need to remember and not accidentally build the project and erase my work.
