### ISSUE TITLE
No Google Cardboard or Daydream support, even as Polyfill?

### ISSUE THREAD

**Issue by ibrews** [MozillaReality/unity-webxr-export#387]
When I try to enter VR on a Pixel 2 XL (set to use Daydream) or a Samung Galaxy S8 (set to use Cardboard), in both cases it 'enters' VR but all I see is a black screen. Confirmed on both phones that other WebXR experiences, such as aframe, load fine.

**Comment by FreekLabs** [comment]
interested in a solution for this as well, discovered it works very well with Samsung Internet on android LG and Samsung phones, would be great to get it to render in Chrome as well.

**Comment by ibrews** [comment]
noticed that it does register if using Firefox too, but yeah Chrome just gives a black screen (A-Frame does work with Chrome). Even in Firefox though, hitting the 'gear' button doesn't take me to the Cardboard set-up the way other WebVR sites do.

**Comment by FreekLabs** [comment]
thanks for that, did not check with FireFox on Android before, it works (feels like it's slightly loosing frame rate in comparison with Samsung Internet), tested it on Magic Leap as well in Helio 0.98, unfortunately gets stuck at "Made with Unity" stage and never starts, other VR examples created with immersive-web libs are working however with very low frame rate, loosing spatial tracking.

**Comment by FreekLabs** [comment]
Vive Cosmos getting no gyro and no controllers, renders the world in headset and shows split screen in browser but no looking around or interaction possible. (tested on https://mixedreality.mozilla.org/unity-webxr-export/Build/)
