### ISSUE TITLE
Sample Scene not Working on Fresh Project

### ISSUE THREAD

**Issue by enesbil** [MozillaReality/unity-webxr-export#388]
Hello! It's really great to have an update on this project. I just wanted to check it out and created a fresh unity project. But unfortunately the sample scene is not working on Unity 2019.3.9

I attached an image into this issue. What have I done wrong? 
It seems I need to select a shader for all the Objects/Prefabs. And also which shader was meant to be selected?
![Anmerkung 2020-04-17 160448](https://user-images.githubusercontent.com/5871793/79577656-528b6080-80c5-11ea-80c2-54e2bea2f1ac.png)

**Comment by enesbil** [comment]
Correction: You need to activate URP in order to run this project correctly. Thus, issue has been solved.

**Comment by joostbos** [comment]
The problem also occurs in Unity 2018.4.22 and there I don't see URP in the Package Manager, so I can't import it.

Actions:
Start Unity 2018.4.22
Import the webxr-exporter.unitypackage from the repo (as the version from the Asset Store can only be used in Unity 2019.3.4)
Enable VR support
Switch to WebGL
Open the demo scene.

**Comment by steakpinball** [comment]
In Unity 2018 the URP is called Lightweight Render Pipeline (LWRP)
