### ISSUE TITLE
No finger touch support in Cardboard?

### ISSUE THREAD

**Issue by ibrews** [MozillaReality/unity-webxr-export#389]
Trying to build this out to have some use for Cardboard, and coded some functionality based on touch input (as I've done with many Unity-based cardboard experiences). Works fine in 2D mode but stops registering once I go to VR. Strange since it works in https://github.com/immersive-web/webvr-polyfill

Test project:
http://alextestprojects.altervista.org/1/index.html

**Comment by De-Panther** [comment]
Try to use HTTPS instead of HTTP.

I didn't try to use touch on Cardboard mode, but at least it'll solve the Polyfill issue.

**Comment by De-Panther** [comment]
Looking more into this, it seems that we might need to check for XRSession "select", "selectstart" and "selectend" for touch input.
And it might also be relevant for AR sessions.

**Comment by imbible** [comment]
Any progress on this?
@De-Panther  Does your fork support the Cardboard button events?

**Comment by De-Panther** [comment]
The fork should, but there's no working example
