### ISSUE TITLE
MagicLeap Helio 0.98 freeze on splashscreen

### ISSUE THREAD

**Issue by FreekLabs** [MozillaReality/unity-webxr-export#390]
Tested the example on Magic Leap as well in Helio 0.98, unfortunately gets stuck at "Made with Unity" stage and never starts, other VR examples created with immersive-web libs are working. (however with very low frame rate, loosing spatial tracking)

**Comment by fernandojsg** [comment]
Can you share if there are some errors on the console when running it? I don't own a magicleap so I can't test it :\

**Comment by De-Panther** [comment]
My guess is that after the last changes ML Helio should work now. But the controllers won't work. I saw that there's WebXR Polyfill for ML, but I'm not sure if it'll enabled the controllers. (And I don't have a device to check this)

**Comment by FreekLabs** [comment]
I did update the magic leap in the meantime and have done two tests both running with a glitch, in 2d mode things were very slow, however once in VR mode, things moved with a surprisingly good speed, as on a mobile, with the controller working too but with one major glitch, both eyes get rendered on the left eye of the magic leap, with nothing on the right eye, very trippy stuff ;)

**Comment by FreekLabs** [comment]
amazing work btw! let me know how I could help on fixing this new issue on magic leap? cheers

**Comment by De-Panther** [comment]
You can try this fork:
https://github.com/De-Panther/unity-webxr-export
https://de-panther.github.io/unity-webxr-export
It has support for AR (immersive-ar session).
Someone already tested it with ML in the past and it worked on both eyes, only the controllers didn't work. So it'll be interesting to know if now they do work.
We are working on merging features from there.

How did you managed to run this repo on ML? Did you made some changes, or does immersive-vr also works on ML, and not just immersive-ar? is the background is the skybox or is it see-through?

In the other repo I added immersive-ar support, another two cameras with Clear Flags set to don't clear, and another change in webxr.js to the DOM canvas context, but the last change was for handheld devices.
