### ISSUE TITLE
Vive Headset not working. Am I missing some set-ups?

### ISSUE THREAD

**Issue by voblinggit** [MozillaReality/unity-webxr-export#393]
Using Unity2019.3.6f1, I followed the full instructions of the WebXR but it doesn't work with our HTC Vive. I'm currently using the Mozilla Browser for this.

Still searching the ways on how to make this work.

**Comment by De-Panther** [comment]
Does the samples at
https://immersive-web.github.io/webxr-samples/
Or https://mixedreality.mozilla.org/hello-webxr/
Works for you?

**Comment by voblinggit** [comment]
> Does the samples at
> https://immersive-web.github.io/webxr-samples/
> Or https://mixedreality.mozilla.org/hello-webxr/
> Works for you?

For the https://mixedreality.mozilla.org/hello-webxr/
This is what the logs say and the vive headset is not working.
![image](https://user-images.githubusercontent.com/43529437/80363964-a4976780-88b7-11ea-9f04-611e85d053c1.png)

For the https://mixedreality.mozilla.org/hello-webxr/
There's no logs and the vive headset is also not working.

We also tried not opening the steam vr then opened the browser, and also tried opening the steam vr then opening the browser.
