### ISSUE TITLE
Unable to enter fullscreen

### ISSUE THREAD

**Issue by TheoSanden** [MozillaReality/unity-webxr-export#397]
Hi!
I don't know if this is the right forum so please tell me if this issue is outside of this scope!

I've tried building the Desert scene and simply opening it in the Mozilla Reality browser doesn't seem to work.

I get the "Enter Vr" Icon as expected, however when I press it I'm presented with a 2d view of the scene instead of entering VR mode.

(Sorry for the bad captures)

*When the project has loaded*
![IMG_20200504_150716](https://user-images.githubusercontent.com/26997845/80969633-38b68100-8e1a-11ea-9220-c3ddf9a2d0d9.jpg)

*When pressing the VR button*
![IMG_20200504_150826](https://user-images.githubusercontent.com/26997845/80969733-5c79c700-8e1a-11ea-9794-b1932fa48bac.jpg)

Is this a normal behaviour or am I missing something?

**Comment by De-Panther** [comment]
You should use HTTPS server instead of HTTP.

On HTTP the plugin would try to use polyfill, and it seems that in Mozilla Reality the polyfill tries to use Cardborad(Which I guess is a bug in the polyfill or in Mozilla Reality).

**Comment by TheoSanden** [comment]
Thank you for the quick reply! I will try that! it will take some trickery to get it to run with https but I hope it works :)

**Comment by fernandojsg** [comment]
People are still struggling with this issue, and even more now that oculus has removed the webvr support so the polyfill can't use it either.
I believe we need to specify it **strongly** on the readme as well as trying to implement some message on the app similar to what threejs does right now when you don't have https connection.

**Comment by De-Panther** [comment]
True.
Maybe also add a simple solution to run local HTTPS server?
I'm using this [http-server](https://www.npmjs.com/package/http-server) for local tests. Just needs to create SSL cert and key, and make sure to run with no cache. I guess that there are even simpler solutions.
