### ISSUE TITLE
GameObject.FindGameObjectsWithTag does not seems to be working

### ISSUE THREAD

**Issue by brunoshine** [MozillaReality/unity-webxr-export#398]
Hi,

On one of the projects we use GameObject.FindGameObjectsWithTag to locate GameObjects and make changes to them. Running inside Unity the scripts using this method work. But whenever we export to webGL using WebXR, this stop working and we get a "did not find game objects with tag [tag_name]" log on the browser.

any thoughts on this?
Thanks
Bruno

**Comment by De-Panther** [comment]
Were they the default (like "MainCamera") or custom tags?

**Comment by brunoshine** [comment]
Hi,
I'm using custom tags.
