### ISSUE TITLE
Demo scene only left eye on HTC Vive

### ISSUE THREAD

**Issue by joostbos** [MozillaReality/unity-webxr-export#399]
As the title already indicates, when I run the demo scene it only renders the left eye. RIght eye is black.

[Edit]Sorry, that's very limited information. Been fighting with the Getting Started guide for half an hour so I got a bit frustrated.

It happens when I run the scene in the editor, Unity 2019.3.4

**Comment by fernandojsg** [comment]
Does that happens also on the build on the browser?

**Comment by joostbos** [comment]
The build is not recognized as VR at all. I can move around with the arrow keys, but I don't get the VR icon in the bottom right corner and I don't get the Allow VR popup in Firefox. When I run the build that was included in the download from github I do get the icon and the popup, but nothing happens when I click on the icon.

In Unity 2018 I have been able to get it running. What happens there is that when I do Build and Run I get the Allow VR popup, If I then click the VR icon nothing happens. I have to tick Remember when I allow VR content and then reload the file. Then the second time I can click the icon and it goes to the headset and everything works fine. That does not work in the UNity 2019 build from github.

**Comment by De-Panther** [comment]
Does the demo works for you? https://mixedreality.mozilla.org/unity-webxr-export/Build/
Do you run your tests using HTTPS?

**Comment by joostbos** [comment]
The demo works using the two-step mechanism I described above. First run it does not work, click Remember and Allow VR content and then reload and then it works fine.

The URL when doing build and run is localhost:<<portnr>>, I don't see http or https, but Firefox shows that it is not secure, so I think  http.

**Comment by deliciouslyevil** [comment]
I've had the same problem with the Oculus.  I've tried opening in several Unity versions (2019.3.4f1, 2019.3.5...).  I had to add the packages from GitHub to a Universal Pipeline Template to get the materials to render, but then the right eye doesn't work.  I remove the Universal RP package, add the Lightweight RP then it works.  So might be a problem with the URP?
