### ISSUE TITLE
Support for XR Interaction Toolkit

### ISSUE THREAD

**Issue by knightcube** [MozillaReality/unity-webxr-export#410]
As per the setup docs [here](https://github.com/MozillaReality/unity-webxr-export/blob/master/docs/xr-testing.md), it will work with the following 2 packages
- Oculus Desktop
- OpenVR Desktop
Both of these are going to get deprecated in Unity 2020.1. The XR Interaction Toolkit will be incredibly helpful for taking user inputs. Currently, is there any support for gaze input?

**Comment by TheBricktop** [comment]
the eye tracking or just head ray?

**Comment by knightcube** [comment]
Head ray will be good

**Comment by tz18** [comment]
@De-Panther has said he is working on this in his fork: https://github.com/De-Panther/unity-webxr-export/
