### ISSUE TITLE
Sample scene black using Quest browser and Mozilla Reality on Quest

### ISSUE THREAD

**Issue by keepingitneil** [MozillaReality/unity-webxr-export#411]
Hey team, I've build the sample desert scene and hosted the result here: https://games.gamechef.io/8f73d5c4-20fb-4cab-bfbf-d5664e19df9f/index.html

I'm using the package from the asset store. When I run this game on my computer browser using the emulator, things work as expected. But on Quest I get a black screen when entering VR. Any idea?

**Comment by keepingitneil** [comment]
I was able to fix this by using the newest source to create the unity package (vs. the one currently published on the unity asset store which was not working)

Now it's working great: https://gamechef.io/game/bowman_vr

**Comment by chamx2** [comment]
Hello @keepingitneil what do you mean by " I was able to fix this by using the newest source to create the unity package" ?
Did you export the unity package on this github repo on top of the downloaded one on unity? 
Since I'm experiencing this as well.

Many thanks!

**Comment by keepingitneil** [comment]
Hey @chamx2 I basically built the packages myself from master. You can see a difference in the webxr.js files between master and what get's built into your project from the unity asset store version.

**Comment by chamx2** [comment]
I got it working on my machine as well, thank you @keepingitneil
