### ISSUE TITLE
How do I map Oculus Quest's Thumbsticks?

### ISSUE THREAD

**Issue by ws18** [MozillaReality/unity-webxr-export#413]
EDIT: the WebXR documentation has interesting diagram: https://immersive-web.github.io/webxr-gamepads-module/images/xr-standard-mapping.svg

The mapping on the buttons[i] ARE CORRECT. However, the problem is that I have no idea on how to access the axis for the thumbsticks. Any solution?

**Comment by DaviisLV** [comment]
Same problem for build, any success with this?
