### ISSUE TITLE
After the update on Oculus Quest Browser, WebXR Export has stopped working

### ISSUE THREAD

**Issue by ws18** [MozillaReality/unity-webxr-export#416]
I had my application up and 100% running. Yesterday I noticed that Oculus Quest Browser updated itself and now, when I click on the symbol on the bottom right to launch "VR Mode" I get a black screen. If I return to web mode it works again.

I also tested the WebXR Exporter example, it doesn't work anymore.

**Comment by meghjagad007** [comment]
I am also facing the same issue after yesterday's Oculus Quest Browser update

**Comment by oculuswebvr** [comment]
Same issue here

**Comment by ExpoXR** [comment]
Same issue too

**Comment by octopus8** [comment]
Hey there everyone. I am just getting started with this exporter and I believe I encountered this issue. I know this sound crazy, but try enabling the "Splash Screen". This is definitely a bug, but I believe this workaround worked for me.

**Comment by louspawn** [comment]
> 
> 
> Hey there everyone. I am just getting started with this exporter and I believe I encountered this issue. I know this sound crazy, but try enabling the "Splash Screen". This is definitely a bug, but I believe this workaround worked for me.

For me this workaround didn't work, and I had this option enabled already in my project. Still getting a black screen exactly as @ws18 described.

**Comment by DoctorBambi** [comment]
I'm running into this issue as well. Just used the included test scene, everything works fine on Build and Run on PCVR and then once fully hosted it still works on PCVR. But when I go to run the game on Quest through the Oculus Browser, all I get is a black screen. The audio still plays and I believe the hand models are anchoring and moving with the controllers, it's just not rendering anything to the headset. I also tried the Firefox Reality Browser and get the same result.

GameChef was able to get past this issue by setting the allowvr="yes" and allow="xr-spatial-tracking" attributes of an iframe that references the index.html file of the hosted game. They have a blog post about it [here](https://medium.com/@gamechefio/how-to-enable-webxr-in-an-iframe-in-react-509759f18125).

Sadly, adding these components did not fix the issue for me, maybe it will help someone else though.

**Comment by adrianstaude** [comment]
Struggling with this as well. Downloading and hosting the Sample Project funnily enough works. Integrating my own scene into the very same project and hosting it on the very same server results in a black or blue screen, depending on camera background settings. Sound is running though and non-VR preview shows the scene.

**Comment by louspawn** [comment]
Any news on this? Still a blocking issue...

**Comment by Jocyf** [comment]
Facing the same problem using Unity 20018.4.23. It works on the editor and on Firefox in windows using Oculus link, but in oculus browsers I get a black screen. It makes WebXR plugin unusable.
It's a pitty, just get it working with free movement using the sticks and raycast interaction... all for nothing if doesn't work in the oulus browsers... snif!
More things... this repo has some few errors and in order to read the stick values I had to change the original xrcontroller code a little bit. I takes me ages to figure out how to read these thumbstick values...

**Comment by prasetion** [comment]
facing the same issue, import from asset store, enable URP, try it in firefox reality in oculus quest, and got black screen. But i think the controller is still working

**Comment by Jocyf** [comment]
> facing the same issue, import from asset store, enable URP, try it in firefox reality in oculus quest, and got black screen. But i think the controller is still working

In my case it was because the antialiasing in the graphics. I tried in Builtin rendering with no antialiasing and it worked (can't remember if it worked in URP)

**Comment by prasetion** [comment]
> > facing the same issue, import from asset store, enable URP, try it in firefox reality in oculus quest, and got black screen. But i think the controller is still working
> 
> In my case it was because the antialiasing in the graphics. I tried in Builtin rendering with no antialiasing and it worked (can't remember if it worked in URP)

when you tried in Builtin rendering with no antialiasing, did you try it in Quest?

**Comment by Jocyf** [comment]
> when you tried in Builtin rendering with no antialiasing, did you try it in Quest?
Yes. It works, but the render quality is the worst. On the other side I can't get it working -using this sene dem- at 72fps.

**Comment by DaviisLV** [comment]
> Facing the same problem using Unity 20018.4.23. It works on the editor and on Firefox in windows using Oculus link, but in oculus browsers I get a black screen. It makes WebXR plugin unusable.
> It's a pitty, just get it working with free movement using the sticks and raycast interaction... all for nothing if doesn't work in the oulus browsers... snif!
> More things... this repo has some few errors and in order to read the stick values I had to change the original xrcontroller code a little bit. I takes me ages to figure out how to read these thumbstick values...

How did you managed to get thumbstick values? I also trying to get them work, but whiteout success. It works in editor, but fails to work in build for me..

**Comment by prasetion** [comment]
I tried the project from github, i open it in unity, and open the sample scene, at first build, i got black screen. But when i remove the desert(?) model, and try to build again, it works. no black screen in quest. Hope someone try the same way like what i have done before, and share the result.

**Comment by Jocyf** [comment]
Most of the time, black screen has to do with antialiasing or some material shader (I used a lot legacy difuse because it works fine, sometimes standard materials for particles for example, fails and you get black screen too)

**Comment by jairovskaya** [comment]
> I'm running into this issue as well. Just used the included test scene, everything works fine on Build and Run on PCVR and then once fully hosted it still works on PCVR. But when I go to run the game on Quest through the Oculus Browser, all I get is a black screen. The audio still plays and I believe the hand models are anchoring and moving with the controllers, it's just not rendering anything to the headset. I also tried the Firefox Reality Browser and get the same result.
> 
> GameChef was able to get past this issue by setting the allowvr="yes" and allow="xr-spatial-tracking" attributes of an iframe that references the index.html file of the hosted game. They have a blog post about it [here](https://medium.com/@gamechefio/how-to-enable-webxr-in-an-iframe-in-react-509759f18125).
> 
> Sadly, adding these components did not fix the issue for me, maybe it will help someone else though.

Same here with the Desert sample. Everything works with PCVR Oculus Quest + Link. But on Quest2 I got the black screen when testing on Firefox Reality 12 browser and Oculus Quest Browser; sound still playing on the background. Unity 2019.4.13

**Comment by enes-oerdek** [comment]
Hey folks, a solution has been provided here: https://github.com/MozillaReality/unity-webxr-export/issues/411

On the Unity Asset Store an old release is published, which causes these issues. You can just update your WebXR-Exporter using the master branch of this repository. Afterwards everything should work fine.
