### ISSUE TITLE
does this asset work with unity projects that are version 2020 or only 2019 and 2018?

### ISSUE THREAD

**Issue by ghost** [MozillaReality/unity-webxr-export#419]

**Comment by ronforbes** [comment]
In my experience, in-editor playback on an Oculus Quest via Link doesn't work for me. I needed to use the 2019 version of Unity. 

Also, even on the 2019 version, the new XR Plugin Management package still didn't work for me. I needed to use the legacy XR setting at Project Settings > Player > XR Settings > Virtual Reality Supported. Then I enabled Oculus.

At that point, I could start Link on my Quest and have my headset and controllers drive in-editor playback. Hope that helps someone and would love to see v2020 supported soon!

**Comment by De-Panther** [comment]
There's Unity 2020 support for WebXR in this repo: https://github.com/De-Panther/unity-webxr-export
