### ISSUE TITLE
cannot read property 'transform' of null

### ISSUE THREAD

**Issue by soldier24** [MozillaReality/unity-webxr-export#433]
Hello,
I am trying to get webvr working for my project.
I have imported the package and put it in my project and exported it so that I can access it in oculus browser. (with the webxr export template)
However when I start it I get to see the game in the browser of Oculus, when I press the VR button I see nothing. When I briefly turn my VR glasses off and on, I see the following error message.

> cannot read property 'transform' of null

I think its somewhere in a javascript file that makes VR possible in supported browsers.
Because of this I cannot make a VR experience in unity for web browsers while I would like to try it.
I am using the latest version that is available in the unity asset store
I make my project in unity 2019.4.14f1 on windows 10

**Comment by soldier24** [comment]
The problem is solved. 😉

**Comment by Akila-ITGit** [comment]
How the problem was solved. Me too facing the same error @soldier24
