### ISSUE TITLE
Headset display goes gray when launching from the browser

### ISSUE THREAD

**Issue by tobinP** [MozillaReality/unity-webxr-export#435]
First I confirmed that both of these work with the headset:

https://mixedreality.mozilla.org/unity-webxr-export/Build/
https://immersive-web.github.io/webxr-samples/immersive-vr-session.html

My test project displays correctly in the headset when launching from the unity editor but when I "build and run" in unity and then press the "Enter VR" button in the browser the display in the headset goes completely gray.  If I move the headset around while looking at the desktop browser I can see the scene updating accordingly.  The hands track and animate correctly too.

No errors in the browser console.

Some specs:
- Unity 2019.3.5f1 URP
- Microsoft Edge 87
- Valve Index
- SteamVR beta 1.15.12
- Current openXR runtime set to SteamVR

Any troubleshooting tips are appreciated.

**Comment by hg111** [comment]
Having the same issue on Quest 2. Did you ever get this to work?

**Comment by tobinP** [comment]
I wasn't able to get it to work by following the instructions to create a new unity project.

My workaround was to download [this sample webXR unity project](https://github.com/webaverse/unity-webxr-export-plugin/blob/master/docs/project-setup.md) , then modify it with my own content.

**Comment by De-Panther** [comment]
You can also use this
https://github.com/De-Panther/unity-webxr-export
