### ISSUE TITLE
VR Not working - No 'Activate VR interface button

### ISSUE THREAD

**Issue by topofsteel** [MozillaReality/unity-webxr-export#437]
I began by republishing the example scene. There is no Allow VR prompt and I don't get the enable VR interface button in the lower right corner. Did I miss a step? Thoughts? Thanks.

http://www.virtualziggurat.com/Projects/WebVR/index.html

**Comment by shujip** [comment]
I have same issue. Did you solve it?

**Comment by LuZongkuan** [comment]
So am I.Although it works fine in the Unity 2019.4.6f1 editor

**Comment by topofsteel** [comment]
Your host doesn't support some of the features needed. I couldn't dig up the specifics now but I'll look for the details later today. I believe Cloudflare supports the requirements but I never worked through it. I reply back with the specific issue when I find it.

**Comment by topofsteel** [comment]
Feature-Policy: xr-spatial-tracking

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/xr-spatial-tracking](url)

**Comment by De-Panther** [comment]
This repo last update was 2 years ago.
There are alternatives...

**Comment by topofsteel** [comment]
I don't think there are any issues with the original code or repo. It just uses features not supported by many hosts.

**Comment by De-Panther** [comment]
The requirement of the backend for WebXR to work, by default, is to run from a secured context (HTTPS).

The header you linked to is not a must. So unless they forcefully restrict this for some reason, that shouldn't be an issue.

* Just pointing out that I'm talking about parent page. running from an iframe does requires `xr-spatial-tracking` in the `allowlist` of the iframe

**Comment by LuZongkuan** [comment]
> 我不认为原始代码或存储库存在任何问题。它只是使用许多主机不支持的功能。
Maybe you're right.I switched to Firefox Reality browser on my desktop,it works.

**Comment by LuZongkuan** [comment]
> I don't think there are any issues with the original code or repo. It just uses features not supported by many hosts.

Maybe you're right.I switched to Firefox Reality browser on my desktop,it works.
