### ISSUE TITLE
Not Working on iPhones

### ISSUE THREAD

**Issue by lijualivenow** [MozillaReality/unity-webxr-export#439]
Not Working on iPhones. AR button is disabled on iOS and VR not working on both safari and firefox.

**Comment by sakshi-oodles** [comment]
> Not Working on iPhones. AR button is disabled on iOS and VR not working on both safari and firefox.

Hi Liju,
is there any chance webxr exporter dessert scene working on iPhone?
Actually, I was also developing webxr demo for iPhone and cardboard VR and it also not working on my end.
