### ISSUE TITLE
Uncaught ReferenceError: UnityLoader is not defined

### ISSUE THREAD

**Issue by Syltas** [MozillaReality/unity-webxr-export#444]
Whenever I try to build the Unity project on my Windows machine to have a look at it in the browser, I get an infinite loading Screen and the error: "Uncaught ReferenceError: UnityLoader is not defined".
In general, no reference in index.html like "%UNITY_CUSTOM_NAME%" works.

I'm pretty new to Unity so I might just have overlooked some pretty basic stuff. Does anyone know where the problem might come from?

**Comment by sixpolys** [comment]
Unity changed the WebGL Template in Unity 2020.1 ([forum thread](https://forum.unity.com/threads/changes-to-the-webgl-loader-and-templates-introduced-in-unity-2020-1.817698/)), you would need to copy the default template from the 2020.1 playbackengines folder and apply the webxr exporter changes there. But i think 2020 is not supported by the exporter.

**Comment by knightcube** [comment]
I got this same issue. How do I resolve this?

**Comment by knightcube** [comment]
So I used Unity 2019 to generate the build and now it is working fine. Looks like 2020 is not supported yet.

**Comment by sixpolys** [comment]
> So I used Unity 2019 to generate the build and now it is working fine. Looks like 2020 is not supported yet.

if you want to use 2020 check out this repository:
https://github.com/De-Panther/unity-webxr-export

**Comment by knightcube** [comment]
Thanks for sharing the link. Will check it out.

**Comment by netgfx** [comment]
2021.3.16f1 still has this issue. I replaced the files from the above link but still the same error with the unityloader
