### ISSUE TITLE
unity WebVR 浏览器画面不同步问题

### ISSUE THREAD

**Issue by gao960** [MozillaReality/unity-webxr-export#445]
Unity开发的WebVR可以在火狐浏览器上运行，能调用起VR效果，在HTC Vive眼镜中看到，但是浏览器页面画面不同步，只显示开始运行的第一帧画面，不知道引起这种情况是我浏览器设置的问题？还是现在版本的浏览器都不支持这个功能了吗？又或者是我们打包或代码中没有调用相应的功能呢？

**Comment by learning-github-zgy** [comment]
请问运行的webxr场景，你在htc vive中打开的是网址吗？还是直接从桌面调用的
