### ISSUE TITLE
Assets/WebXR/Scripts/WebXRCamera.cs(89,26): error CS0117: `UnityEngine.XR.InputDevices' does not contain a definition for `GetDevicesWithCharacteristics'

### ISSUE THREAD

**Issue by lilithebowman** [MozillaReality/unity-webxr-export#449]
Followed these instructions exactly: https://github.com/MozillaReality/unity-webxr-export/blob/master/docs/project-setup.md

`Assets/WebXR/Scripts/WebXRCamera.cs(89,26): error CS0117: 'UnityEngine.XR.InputDevices' does not contain a definition for 'GetDevicesWithCharacteristics'`

`Assets/WebXR/Scripts/WebXRController.cs(278,18): error CS0246: The type or namespace name 'XRInputSubsystem' could not be found. Are you missing 'UnityEngine.Experimental.XR' using directive?`

`Assets/WebXR/Scripts/WebXRController.cs(279,13): error CS0103: The name 'SubsystemManager' does not exist in the current context`

etc...

Freshly imported copy of the project. Can't run or compile due to compiler errors. Using the proper version of Unity the project was made in.

![image](https://user-images.githubusercontent.com/1637212/141213402-24a38d9e-5553-419c-93e6-4e0fecfebcaa.png)
![image](https://user-images.githubusercontent.com/1637212/141214147-b97061c2-9551-4df9-8804-cff1c75b502f.png)

**Comment by De-Panther** [comment]
This repo had no update for more than a year.
There are other WebXR exporters.
https://github.com/De-Panther/unity-webxr-export
