### ISSUE TITLE
Failed to import unity-webxr-export plugin using Unity2020.3 error CS0619: 'XRDevice.isPresent' is obsolete

### ISSUE THREAD

**Issue by 0x3f97** [MozillaReality/unity-webxr-export#451]
Failed to import unity-webxr-export plugin using Unity2020.3 

![image](https://user-images.githubusercontent.com/32476377/144742034-b526c7bc-5b53-46bf-abd6-aa0a0ab7e454.png)

how to fix it ?

**Comment by prasetion** [comment]
you can try this. 
https://forum.unity.com/threads/xrdevice-ispresent-is-obsolete.1057556/

**Comment by 0x3f97** [comment]
thanks, it work
