### ISSUE TITLE
package error

### ISSUE THREAD

**Issue by mmsbba4** [MozillaReality/unity-webxr-export#454]
anyone can help me with this issue
![Capture](https://user-images.githubusercontent.com/42690879/154654604-d2bf808c-8ebc-4756-8c02-c752819d1b11.PNG)

**Comment by wangyin1111** [comment]
![image](https://user-images.githubusercontent.com/22514592/165087727-3eabccec-59a2-4c72-aee2-1d9e9f04dacb.png)
![屏幕截图 2022-04-25 201850](https://user-images.githubusercontent.com/22514592/165087846-b2921462-fba4-46cf-80ad-01c5be4489ac.png)
