### ISSUE TITLE
Consider using Unity's stereo rendering API

### ISSUE THREAD

**Issue by delapuente** [MozillaReality/unity-webxr-export#73]
Current Unity's [camera API](https://docs.unity3d.com/ScriptReference/Camera.html) provides an stereo API without the need of creating two camera instances. The resulting camera would behave like a real camera which is more natural

**Comment by caseyyee** [comment]
Didn't know this existing.  Cool, will look into it.

**Comment by delapuente** [comment]
I think it is not possible. [Documentation](https://docs.unity3d.com/Manual/VROverview.html#UnderstandingTheCamera) says:
> There is no automatic side-by-side view of the left and right eyes. To see a side-by-side view in the Game View, create two Cameras, set one to the left and one to the right eye, and set the viewport of display them side by side.

Anyway, I'm asking [in the forum](https://answers.unity.com/questions/1472180/how-can-i-enable-stereo-rendering-in-webgl.html).

And I open issue #154 for enhancing the camera rigging to mimic the in-editor behaviour of Unity.

**Comment by delapuente** [comment]
I think it is not possible. [Documentation](https://docs.unity3d.com/Manual/VROverview.html#UnderstandingTheCamera) says:
> There is no automatic side-by-side view of the left and right eyes. To see a side-by-side view in the Game View, create two Cameras, set one to the left and one to the right eye, and set the viewport of display them side by side.

Anyway, I'm asking [in the forum](https://answers.unity.com/questions/1472180/how-can-i-enable-stereo-rendering-in-webgl.html).

And I open issue #154 for enhancing the camera rigging to mimic the in-editor behaviour of Unity.
